export const ROUTES = {
  HOME: '/',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/usuarios',
  ADMIN_COURSES: '/admin/cursos',
  ADMIN_SUBJECTS: '/admin/materias',
  ADMIN_PROJECTS: '/admin/proyectos',
  ADMIN_ESP32: '/admin/esp32',
  PROFESSOR: '/profesor',
  PROFESSOR_COURSES: '/profesor/cursos',
  professorCourse: (id: string) => `/profesor/cursos/${id}`,
  PROFESSOR_ATTENDANCE: '/profesor/asistencia',
  professorAttendanceCourse: (id: string) => `/profesor/asistencia/${id}`,
  DASHBOARD: '/dashboard',
  PROJECTS: '/proyectos',
  projectConfig: (id: string) => `/proyectos/${id}/config`,
  LOGIN: '/login',
  REGISTER: '/register',
  RECOVER_PASSWORD: '/recuperar-contrasena',
  CALENDARY: '/calendario',
  PREFERENCES: '/preferencias',
} as const;
